Community Broadcast page updates
trinodb/trino.io pull request #181
Opened 2021-02-25 19:59 UTC by kylefraser

This PR updates the layout of the Community Broadcast page.

These changes were initially discussed on [Slack]( https://trinodb.slack.com/archives/C01GW0QR16Z/p1613595522041100) and were further materialized via discussion with @bitsondatadev 

One of the goals is to highlight more of the podcast content, as opposed to having to click the current "See Past Episodes" button.

Included:
- Call out 'Latest Episode' and embed video
- Grid/Blog style for previous episodes
- Watch/learn links are now icons
- Google Calendar now just displays the 'Agenda' 
- Previous episode cards are limited to 3 bulleted items

<details>
<summary>screenshot</summary>

![screencapture-127-0-0-1-4000-broadcast-2021-02-25-10_53_55](https://user-images.githubusercontent.com/1330423/109191639-5ca9d100-7764-11eb-81f7-f13ad334e5bc.png)

</details>

Related Slack Thread: https://trinodb.slack.com/archives/C01GW0QR16Z/p1613595522041100

2021-02-26 21:34 UTC, mosabua commented on broadcast/index.md
> +## About
remove .. this is redundant

2021-02-26 21:34 UTC, mosabua commented on broadcast/index.md
> +## Watch/Listen
Watch or listen

2021-02-26 21:36 UTC, mosabua commented on broadcast/index.md
> +</a>
Do we need to do a generic RSS feed or something like that a well.. something that works for any podcast app

2021-02-26 21:38 UTC, mosabua requested changes
A few tweaks needed but then good to go as a definite improvement!

2021-02-26 21:38 UTC, mosabua commented on broadcast/index.md
> +## Upcoming shows
empty line below and above title

2021-02-26 21:38 UTC, mosabua commented on broadcast/index.md
> +## Latest Episode
Latest episode

and empty line above and below title

2021-02-26 21:38 UTC, mosabua commented on broadcast/index.md
> +## Previous Episodes
Empty line above and below

Previous episodes

2021-03-01 16:28 UTC, bitsondatadev approved these changes
Spoke with Kyle directly about fixing the ordering of "previous episodes." Otherwise looks fantastic!

2021-03-01 21:50 UTC, closed without merging