Add Stripe testimonial, logos, and url
trinodb/trino.io pull request #225
Opened 2021-05-20 22:46 UTC by rosewms

2021-05-20 22:47 UTC, rosewms commented on _data/users.yml
> +  url: https://stripe.com/
Should I link to the Stripe support site where they have a continued explanation: https://support.stripe.com/questions/why-has-the-format-of-object-value-in-my-sigma-query-result-changed

2021-05-20 23:00 UTC, mosabua requested changes

2021-05-21 17:22 UTC, mosabua approved these changes
Good to go @martint

2021-05-21 17:28 UTC, martint commented
Please squash the commits and add a link to https://support.stripe.com/questions/why-has-the-format-of-object-value-in-my-sigma-query-result-changed in a comment for reference, like we do for other entries.

2021-05-25 15:14 UTC, rosewms commented
@martint fixed, thanks for your help.

2021-05-25 16:06 UTC, merged