Add blog post from Comcast
trinodb/trino.io pull request #252
Opened 2021-10-01 15:37 UTC by posulliv

2021-10-02 08:16 UTC, mosabua requested changes
A bunch of nits and suggestions. 

Beyond that I think you need some sort of Summary at the end.

And also .. can we also get a user testimonial and logo for the site? I can help with details or even send the PR if you supply text, URL and logo. See https://trino.io/users.html
cc @bitsondatadev @martint

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +select
For here and all statements .. use uppercase SQL keywords like in the docs

SELECT count(a.c) 
FROM
...

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +But adding a predicate caused the performance problem to appear:
add in this sentence what the predicate is..

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +For the simple version of the query performing poorly, the same stage has the
well.. reword .. this is for the more complex version with the predicate right?

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +determine why that was and exactly what was using additional CPU.
was to determine possible reasons.

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +We generated a few jstack and JFR profiles of the Starburst Java process from
link to jstack maybe 

and what is JFR (spell it out)

And 

of the Trino Java process

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +profiles, we found no obvious problem; Trino performed as expected.
problem. Trino

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +Notice in the above screenshot, some workers have tasks that only use up a few
You can leave out the "Notice in the above screenshot"

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +the JVM will refuse to do so any more and will run the method in interpreted
change to present tense

the JVM refuses .. and runs in the much slower interpreted mode.

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +the typical difference one would expect for compiled versus interpreted code,
remove "one would expect"

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +### Initial Results
Initial results

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +The CPU used by individual tasks is much more uniform as shown in the following
is much more uniform:

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +## Code Cache
Code cache

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +cluster was up for a few days and there would be a few workers where tasks
few days, and there

2021-10-02 08:16 UTC, mosabua commented on _posts/2021-10-06-jvm-issues-at-comcast.md
> +## Off Heap Memory Usage
Off heap memory usage

2021-10-03 04:38 UTC, bitsondatadev commented
@mosabua just so it's clear @posulliv is a support engineer who worked with Comcast but it would be cool if Comcast could add their testimonial. 

Padraig can you speak with David and Saj to see if they would be interested in adding the Comcast logo and testimonial on the Trino site?

2021-10-03 10:24 UTC, mosabua commented
I am of course aware of the role of @posulliv ...

2021-10-04 20:19 UTC, posulliv commented
@mosabua thank you for the review and many comments! I went through and applied them all. I also added a brief summary at the end.

2021-10-04 20:21 UTC, posulliv commented
I'll check with the Comcast folks about a user testimonial on the Trino site and let you know.

2021-11-03 17:30 UTC, posulliv commented
@mosabua @bitsondatadev is there anything else you need on my end for this post?

2021-11-03 17:46 UTC, mosabua commented
Its up to @martint @dain @electrum and other maintainers to decide on next steps. I can review again if desired.

2021-11-04 14:34 UTC, merged