Add episode 28
trinodb/trino.io pull request #254
Opened 2021-10-05 22:02 UTC by bitsondatadev

2021-10-12 21:08 UTC, mosabua commented on _episodes/28.md
> + *
```
* Misc performance and memory usage improvements
* `SHOW ROLES` fix
* `EXPLAIN ANALYZE` fix for estimate display
*  Numerous improvements for Parquet files in Hive and Iceberg connectors
```

2021-11-09 21:46 UTC, mosabua requested changes

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +The simple view of an event stream will contain a sequential list of events. The
In this simple view an event stream contains a sequential list of events.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +Engineers at Dell labs wanted to find a better abstraction to solve for the
is it Dell Labs ?

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +address this type of constant shift in scaling while also addressing the brittle
scaling, while

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +storage abstractions that even streams use today. This storage abstraction needs
The storage abstraction

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +Their solution is Pravega and the core of Pravega build around modeling streams
Pravega. The core of Pravega models streams built around a storage unit. called a segment.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +sequence of bytes (not events/records). This offers a greater level of
Change sentence to avoid "offer" twice.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +You can use **routing keys** to map events to particular segments. Pravega will
Pravega enforces order

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +enforce order within specific keys but does not guarantee ordering of events
keys, but does

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +Below shows a very nice way of visualizing autoscaling splits and merges as
The following diagram displays autoscaling splits

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +automatically trigger a split, and once the rush hour is over, it will merge
it merges these

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +### Pravega Architecture
architecture

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +to allow for both realtime and historical analytics. The data along a particular
real-time

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +The Pravega Architecture comes with writers groups and reader groups that scale
architecture

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +systems that will be the source and sink. This includes a connector used for
that act as source or sink.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +This week, Pravega will be showing us a demonstration from their own [getting-started](https://github.com/pravega/presto-connector/tree/main/getting-started)
This week the Pravega teams demonstrates an example from their getting started tutorial for the Trino connector.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +## Question of the week: What is the point of Trino Forum and what is the relationship to Trino Slack?
forum.  ??

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +comes from the new Trino Forum by Starburst that Brian and a few others at  have put
hm .. maybe you are using it as name and hence always use "Trino Forum" .. up to you

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +comes from the new Trino Forum by Starburst that Brian and a few others at  have put
by Starburst. Brian and a few other helpers have set this up and started to add content.

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +Community has such a great amount of knowledge accumulated in this Slack channel,
community

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +without a crowdsourcing element. Instead, starting a [Discourse forum](https)
link

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +(not to be confused with Discord) that will act as a central repository of
acts as

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +without a crowdsourcing element. Instead, starting a [Discourse forum](https)
Instead ...  this whole following sections needs to be changed to be a sentence

2021-11-09 21:46 UTC, mosabua commented on _episodes/28.md
> +Blogs and Resources
resources

2021-11-10 20:29 UTC, bitsondatadev commented on _episodes/28.md
> +     desc: "What is the point of Trino Forum and what is the relationship to Trino Slack?"
Trino Forum is part of the title so I'll stick with, "Forum, and"

2021-11-10 22:15 UTC, bitsondatadev commented on _episodes/28.md
> +## Question of the week: What is the point of Trino Forum and what is the relationship to Trino Slack?
should be upper

2021-11-10 22:25 UTC, mosabua approved these changes
Good enough now imho. Let's ship it.

2021-11-10 22:44 UTC, bitsondatadev commented
Hey @martint, this one too 😄.

2021-11-11 05:37 UTC, merged