Add Log4Shell blog
trinodb/trino.io pull request #261
Opened 2021-12-13 22:30 UTC by bitsondatadev

2021-12-13 22:48 UTC, mosabua requested changes

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +and we wanted to inform you that Trino is not affected. Trino does not use log4j
we want to inform

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +in the core engine or runtime classes. There are some connectors that include
too much "some" in this sentence.

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +extra steps to make sure no future iterations of Trino will ever introduce this
Dont say it like that .. just mention that regular security reviews, including code and dependency analysis, are part of the regular development process. And if there are any findings from the community - how to reach out (but that part probably later in the post)

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +## Trino Connectors with the Log4j dependency
connectors

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +you'll notice the log4j dependency pops up in two of the connectors, Accumulo
I think that might be misleading.. you have to do a transitive dependency analysis.. the easiest way is to check a extracted tarball and look in each plugin directory.. there might be more..

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +The Accumulo connector depends on log4j 1.2.17, which although isn't vulnerable
thats not a sentence

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +still no threat even if you are using it. We will remove the uses of this log4j
We are working on removing the dependency as a precautionary measure

and add link to github issue to track that..

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +[that was recently removed](https://github.com/trinodb/trino/commit/2018a94253d48cfdce283538855ee65950f9be3d),
. It was not used in the connector.

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +existence of the dependency in the Elasticsearch connector, it was not used and
Dont repeat it too much.

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +to the build process to ban log4j.
to ban log4j as direct dependency.

Unless we get confirmation that it also bans it as transitive dependency

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +1. Rest assured that there is not vulnerability in your Trino cluster.
no vulnerability

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +We know this is a tough time for many of you. We wish you all the best of luck
Thats weird... it isnt tough .. we just clarified that this was a false alarm.

2021-12-13 22:48 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +systems. If you have any questions, please reach out on the [Trino Slack](https://trino.io/slack.html).
drop "please"

2021-12-13 22:56 UTC, bitsondatadev commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +you'll notice the log4j dependency pops up in two of the connectors, Accumulo
I'll remove the link but just mention it then.

2021-12-13 23:08 UTC, bitsondatadev commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +We know this is a tough time for many of you. We wish you all the best of luck
Well unless they only use Trino, but there are folks using plenty of compromised systems outside of Trino.

2021-12-13 23:53 UTC, electrum commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +and we want to inform you that Trino is not affected. Trino does not use log4j
Bold the text “Trino is not affected”

2021-12-13 23:54 UTC, electrum commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +If you do a search in the Trino repository, you'll notice two direct
Remove extra “are” or otherwise fix

2021-12-13 23:56 UTC, electrum commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +still no threat even if you are using it. We will remove the uses of this log4j
Or change “for best practices” to something like “to avoid any confusion”

2021-12-13 23:59 UTC, electrum approved these changes

2021-12-13 23:59 UTC, electrum commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +2. If you've created your own connectors with one of the affected log4j
connectors -> plugin

2021-12-13 23:59 UTC, electrum commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +Once you've updated, it will be impossible to use log4j2
Maybe remove this. We don’t do runtime enforcement, so custom plugins are still a potential issue.

2021-12-14 00:53 UTC, bitsondatadev commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +Once you've updated, it will be impossible to use log4j2
done

2021-12-14 01:11 UTC, mosabua commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +The Accumulo connector depends on log4j 1.2.17, which although isn't vulnerable
This is still weird since it has two which sections in one sentence.

2021-12-14 02:28 UTC, merged

2021-12-14 05:15 UTC, hashhar approved these changes
An errata. Pretty nice otherwise.

2021-12-14 05:15 UTC, hashhar commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +to the build process to ban log4j as a direct dependency.
The rule also catches transitive dependencies.

2021-12-14 10:29 UTC, losipiuk commented on _posts/2021-12-13-log4shell-does-not-affect-trino.md
> +including code and dependency analysis, are part of the regular development
drop second `regular`