add QazAI customer blog
trinodb/trino.io pull request #300
Opened 2022-06-03 04:54 UTC by brianzhan

2022-06-03 17:32 UTC, mosabua requested changes

2022-06-03 17:32 UTC, mosabua commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +we will set `retry_policy=QUERY` in `config. properties`.
we set

2022-06-03 17:32 UTC, mosabua commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +
Remove redundant empty lines

2022-06-03 17:32 UTC, mosabua commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +kuspayev@aifund.kz
Not sure we should do that, lets remove the email.. instead maybe mention the username on the trino slack and get users to ask you there .. also maybe refer to the project-tardigrade channel

2022-06-07 21:28 UTC, mosabua commented
@brianzhan are you addressing the review notes?

2022-06-08 03:28 UTC, brianzhan commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +create table hive.test.dvd_rental
I don't think SQL should necessarily be uppercase- we actually turn things to lowercase with the Galaxy formatter

2022-06-08 04:27 UTC, mosabua commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +create table hive.test.dvd_rental
The standard we follow in all Trino docs is uppercase .. please just follow it for readability reasons.

2022-06-08 05:07 UTC, mosabua commented on _posts/2022-06-02-building-a-modern-data-stack-for-qaz-ai.md
> +delivered the data to business units via our datamart built on Clickhouse (for optimal delivery speeds). Over time, we were dragged down by the slower speeds and high costs of running Hive, and start
wrap please

2022-06-08 05:08 UTC, mosabua approved these changes
I think this is good to go now. We should probably update the date (filename) just before we merge to whatever day ...

2022-06-08 13:45 UTC, arhimondr approved these changes
@brianzhan please update the date and it should be ready to go

2022-06-08 18:10 UTC, merged