Add contributors list and update slack counts
trinodb/trino.io pull request #301
Opened 2022-06-07 20:16 UTC by bitsondatadev

Add a simple contributor list image and update the community member counts.

![Screen Shot 2022-06-07 at 3 16 03 PM](https://user-images.githubusercontent.com/8547669/172474202-829b9ea4-3140-4c81-8478-33292bf59945.png)
.

2022-06-07 21:59 UTC, mosabua requested changes

2022-06-07 21:59 UTC, mosabua commented on community.md
> +      <h2>Trino Contributors</h2>
contributors

2022-06-07 21:59 UTC, mosabua commented on community.md
> +              <p>Improve existing functionality or even add your own feature.</p>
functionality, or

2022-06-07 21:59 UTC, mosabua commented on community.md
> +      <p>A huge amount of gratitude goes out to all of our contributors. Without you, none of this is possible.</p>
to all contributors

2022-06-07 21:59 UTC, mosabua commented on community.md
> +        <object type="image/svg+xml" data="https://contrib.rocks/image?repo=trinodb/trino&max=200&columns=10"></object>
Would it be safer to just use an image and update it now an then .. this would avoid the dependency on that system being up and running and available

2022-06-11 04:48 UTC, mosabua commented on community.md
> +        <!--img src="../assets/images/community/contributors.svg" alt="Trino Contributors" /-->
why the comment?

2022-06-13 22:09 UTC, bitsondatadev commented on community.md
> +        <!--img src="../assets/images/community/contributors.svg" alt="Trino Contributors" /-->
removed

2022-06-14 01:56 UTC, mosabua approved these changes
Looks good now.

2022-06-17 18:18 UTC, merged