Add PTF blog post
trinodb/trino.io pull request #313
Opened 2022-07-11 17:07 UTC by colebow

Blog post to cover polymorphic table functions. Will update the file name & release date once we're ready to merge.

2022-07-11 18:14 UTC, mosabua requested changes

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +connectors. They go by the name `query`, and take a single argument, being the
I think by them time this goes live we have BigQuery and Elasticsearch as well..

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +
Sentence here?

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +needs to be written so that it works on that connector. On the opposite and more
nope .. it needs to work in the underlying data source .. the connector only passes it through

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +roadmap, we’re working on query pass through for ElasticSearch and BigQuery, and
this might be in already ..

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +through to the connector, with Trino doing none of the work. With an operator,
via the connector to the underlying database

2022-07-11 18:14 UTC, mosabua commented on _posts/2022-07-11-polymorphic-table-functions.md
> +Community Broadcast on PTFs on July 21st @ 1pm EDT, so tune in then to have your
After the broadcast we should update this post with a link to the episode

2022-07-19 11:38 UTC, kasiafi commented on _posts/2022-07-11-polymorphic-table-functions.md
> +are popular languages that are used to bridge the gap of some of the
a repetition: "popular languages"

2022-07-19 16:18 UTC, colebow commented on _posts/2022-07-11-polymorphic-table-functions.md
> +table reference shows up such as a `FROM` clause:
The second example shows a TF in a `JOIN` clause as well.

2022-07-22 05:17 UTC, mosabua commented
Can we please get this merged.. we really wanted this live prior to the Trino Community Broadcast as a call out for interested people to join us then .. since the TCB is delayed by a week we have a chance to get it live before.. @martint @kasiafi

2022-07-22 06:26 UTC, martint commented on _posts/2022-07-20-polymorphic-table-functions.md
> +  TABLE(another_table_funciton(1, 2, 3))
Typo: funciton

2022-07-22 06:26 UTC, martint commented on _posts/2022-07-20-polymorphic-table-functions.md
> +functions make SQL extensible and act as a bridge between the Trino engine and
“act as a bridge…” is a mischaracterization. That’s one possible application, but there are functions one could write that have nothing to do with external systems or resources, much like any scalar, aggregation or window function

2022-07-22 06:26 UTC, martint commented on _posts/2022-07-20-polymorphic-table-functions.md
> +Besides PostgreSQL, the `query` table function is also available for Druid,
Technically, these are all different functions that happen to have the same name

2022-07-22 06:26 UTC, martint commented on _posts/2022-07-20-polymorphic-table-functions.md
> +an identical function called `raw_query`. You can check out the
It’s not “identical”. It’s equivalent or similar

2022-07-25 11:52 UTC, kasiafi commented
It looks good to me, but I think we need approval from @martint

2022-07-25 19:37 UTC, martint commented on _posts/2022-07-22-polymorphic-table-functions.md
> +“query” argument, it’s pushing the entire query down to PostgreSQL to process
“Pushing” is misleading. That’s usually used in the context of the capabilities of the optimizer. In the case of the query function, it literally executes the query in the remote system without any involvement from the optimizer.

2022-07-25 19:40 UTC, martint reviewed
Minor comment. Other than that, it looks good.

2022-07-25 20:33 UTC, merged