Add blog post for 6/14 meetup
trinodb/trino.io pull request #318
Opened 2022-07-14 20:44 UTC by colebow

...only a month late. We're backdating the post to 6/24 so it's less on top of the other (more important) blog posts that have been rolling out lately.

2022-07-14 20:54 UTC, colebow commented
<img width="894" alt="image" src="https://user-images.githubusercontent.com/104291808/179084241-8760343f-4c30-4e5e-91bb-a77885202b5a.png">

2022-07-14 23:22 UTC, mosabua requested changes

2022-07-14 23:22 UTC, mosabua commented on _posts/2022-06-24-trino-meetup-extract-trino-load.md
> +This past week, Andrii Rosa hosted a virtual Trino meetup on the topic of using
Link to Andriis github profile or website or whatever

2022-07-14 23:22 UTC, mosabua commented on _posts/2022-06-24-trino-meetup-extract-trino-load.md
> +embedded below. The talk dives into the history of Trino as an engine for Batch
Andrii dives into the

2022-07-14 23:22 UTC, mosabua commented on _posts/2022-06-24-trino-meetup-extract-trino-load.md
> +<div class="spacer-30"></div>
Video should be below the fold (more ..)

2022-07-18 16:31 UTC, arhimondr approved these changes

2022-07-19 01:19 UTC, merged