WIP: Add Trino tenth birthday post
trinodb/trino.io pull request #325
Opened 2022-08-03 20:07 UTC by bitsondatadev

This is still a WIP as we don't have all the links live yet so DO NOT MERGE until this description is updated.

2022-08-03 20:07 UTC, bitsondatadev commented on _posts/2022-08-08-trino-tenth-birthday.md
> +below. Starburst is also celebrating by offering free Trino birthday t-shirts
Add link from @monimiller when ready

2022-08-04 20:34 UTC, mosabua requested changes

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +title: "Happy 10th Birthday Trino!"
```suggestion
title: "Happy tenth birthday Trino!"
```

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +Presto, the distributed big data query engine created at Facebook in 2012. We
```suggestion
Presto, the distributed big data SQL query engine created at Facebook in 2012. We
```

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +the SPI abstracted metadata and storage, among other interfaces to different
```suggestion
the SPI abstracted metadata and storage access to different
```

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +systems, making Trino a suitable system to query an entire data ecosystem from
```suggestion
systems, making Trino a suitable engine to query an entire data ecosystem from
```

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +development from the original project and has added an array of features that
```suggestion
development from the original project and added an array of features that
```

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +we’ve listed out in the evolution of the Trino architecture blog post.
link

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +our annual Trino Summit in November!
link to blog post on trino.io

2022-08-04 20:34 UTC, mosabua commented on _posts/2022-08-08-trino-tenth-birthday.md
> +[sign up for our hybrid event Trino Summit November 10th, 2022](https://www.starburst.io/info/trinosummit/).
```suggestion
[sign up for our hybrid event, Trino Summit, on the 10th of November 2022](https://www.starburst.io/info/trinosummit/).
```

2022-08-08 15:10 UTC, merged