Add Trino fault tolerance architecture post
trinodb/trino.io pull request #329
Opened 2022-08-10 10:56 UTC by bitsondatadev

2022-08-10 14:12 UTC, linzebing commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +as now we can process a subset of data at a time. Executing memory intensive
```suggestion
as now we can process a subset of data at a time. Executing memory-intensive
```

2022-08-10 14:12 UTC, linzebing commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +`trino-exchange` plugin, supporting local filesystem, AWS S3, Azure Blob
It has been renamed already. Also local filesystem is misleading --- it's not applicable to multiple workers.
```suggestion
`trino-exchange-filesystem` plugin, supporting AWS S3, Azure Blob
```

2022-08-10 14:12 UTC, linzebing commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +implementation takes full advantage of S3 asynchronous APIs to overlap
```suggestion
implementation takes full advantage of asynchronous APIs to overlap
```

2022-08-10 14:12 UTC, linzebing commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +of storage tiers to further enhance exchange performance.
```suggestion
The exchange APIs defined in the Trino SPI are designed to be extensible, and allow for the community to build a distributed buffering service to further enhance exchange performance.
```

2022-08-10 16:55 UTC, bitsondatadev commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +`trino-exchange` plugin to allow for the community to build a distributed
```suggestion
`trino-exchange-filesystem` plugin to allow for the community to build a distributed
```

2022-08-10 16:56 UTC, bitsondatadev commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +## Fault tolerance
```suggestion
## Fault-tolerance
```

2022-08-10 16:56 UTC, bitsondatadev commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +There are now two levels of fault tolerance into Trino:
```suggestion
There are now two levels of fault-tolerance into Trino:
```

2022-08-10 16:57 UTC, bitsondatadev commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +first-class support for batch processing. Featuring fault tolerance and flexible
```suggestion
first-class support for batch processing. Featuring fault-tolerance and flexible
```

2022-08-11 03:20 UTC, linzebing approved these changes

2022-08-24 18:47 UTC, martint commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +at stage boundaries.This opens up a lot of new opportunities around failure
Space after period

2022-08-24 18:47 UTC, martint commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +The exchange APIs defined in the Trino SPI are designed to be extensible, and allow for the community to build a distributed buffering service to further enhance exchange performance.
> and allow for the community to build 

It's not "us vs the community". I would rephrase to explain that this allows for customized implementations of the exchange spooling APIs, and that future directions might involve building a dedicated buffering service using tiered storage (memory, ssd, object store)

2022-08-24 18:47 UTC, martint commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +With fault tolerance built into Trino, long-running batch queries now can enjoy
This is not quite true. Stable and predictable completion times depend on many other factors than granular retries (concurrent workloads, resource management, performance of dependent systems, etc).

Also, "landing time" is a very vague term (specifically used within FB), but I don't know if it's in common usage in the industry. Is it defined elsewhere?

2022-08-26 05:29 UTC, martint commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +With the exception of grouped execution,which applies to limited scenarios like
Space after comma

2022-08-26 05:29 UTC, martint commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +By maintaining a deduplication buffer with the ability to spill to external
"deduplication buffer" needs some clarification. It's not obvious what that means for someone unfamiliar with the implementation

2022-08-30 23:02 UTC, mosabua requested changes
Overall there is a lot of good content in here but the post misses an arc for a story line. Ping me to chat and discuss. Might be a bigger refactor. We need to figure out what we want to communicate .. currently that is not clear to me.

2022-08-30 23:02 UTC, mosabua commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +option for enabling it out using a a [fully managed Trino (Starburst Galaxy)](https://www.starburst.io/platform/starburst-galaxy/),
sorry ... what does this sentence want to say?

2022-08-30 23:02 UTC, mosabua commented on _posts/2022-08-10-architecting-trino-next-gen-etl-engine.md
> +Please reach out to us on [Trino Slack](https://trino.io/slack.html) in the
Drop "Please"

2022-10-29 10:56 UTC, bitsondatadev commented
Oops...Mah bad

2023-04-18 20:57 UTC, mosabua commented
I am closing this .. feel free to reopen if you end up working on it at some stage.

2023-04-18 20:57 UTC, closed without merging