Added Careem in User list
trinodb/trino.io pull request #342
Opened 2022-09-05 11:02 UTC by jatin5251

2022-09-05 11:04 UTC, nineinchnick commented on _data/users.yml
> +    This makes Presto one of the most critical services to serve as a backbone of data access
```suggestion
    Trino is a valuable platform to quickly analyze data. Many data analysts and data scientists 
    use Jupyter Notebooks consistently to write automated reports and schedule queries. 
    This makes Trino one of the most critical services to serve as a backbone of data access 
```

2022-09-06 18:48 UTC, mosabua requested changes
Text and such look good. Images need to be adjusted to the standard sizes 500x400 and 250x200 for the small.

2022-09-08 18:52 UTC, mosabua commented
Looks like the images are now distorted. Can you fix that or am I mistaken. Also please sqaush all commits.

2022-09-15 17:02 UTC, mosabua commented
@jatin5251 did you want us to take over this PR and get it completed?

2022-09-17 10:51 UTC, closed without merging

2022-09-20 07:05 UTC, mosabua commented
@jatin5251 let me know if I should create a replacement PR with the right logo sizes and such and get it merged.

2022-09-20 07:32 UTC, jatin5251 commented
@mosabua i will do it in a week, i am traveling right now. 
thanks for your patience