Add birthday celebration and recap blog
trinodb/trino.io pull request #343
Opened 2022-09-05 12:28 UTC by bitsondatadev

So far I've added the content (aka words/images/videos) for this blog but the formatting is terrible. I really like the concept of adding a bunch of clips in this blog but I wasn't able to make the videos small and sit side by side or something like the [Starburst video resources page](https://docs.starburst.io/videos/index.html) except with the video embedded with a small amount of text under it.

@kylefraser if you could help out with this in any way it would be greatly appreciated.

2022-09-06 21:17 UTC, mosabua requested changes
Lets chat about the layouting .. somehow weird where the div ends and : are placed .. seems to make no sense

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +What an exciting month we had in August! August marked the ten-year birthday of
Too many `!` in this paragraph .. one should be enough

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +chronicled the incredible journey starting with the Presto project's humble
change sentence to present tense.. the video still exists

video that chronicles the incredible journey from the humble beginnings as Presto to the success that Trino is today.

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +covers the potential of these functions in much more detail!
Change ! to .

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +### The early days of Presto and Trino
Empty line after title

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +Step 1: Look up a bunch of research papers to see how others are doing this 📑:
weird character there..

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +Site note: Papers tend to be highly aspirational and skip important fundamentals:
Side note:

2022-09-06 21:17 UTC, mosabua commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +Site note: Papers tend to be highly aspirational and skip important fundamentals:
also why does this sentence end with :

2022-09-08 05:01 UTC, bitsondatadev commented on _posts/2022-09-02-tenth-birthday-celebration-recap.md
> +Step 1: Look up a bunch of research papers to see how others are doing this 📑:
that's a files emoji

2022-09-08 18:59 UTC, mosabua commented
General comment .. the way the post looks now is bad since it has the same image for each video. Either we make it so the previews are different or maybe easier .. just get rid of the funky layout and have a list of texts you have now with a "Play video" button or so.

2022-09-08 20:04 UTC, mosabua requested changes
Lets chat how to best proceed here..

2022-09-09 22:27 UTC, mosabua requested changes
Just a few more minor things to address. Nearly ready.

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +As more marketing around vectorized databases have come up recently many have
```suggestion
As more marketing around vectorized databases has come up recently many have
```

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +interesting time as [Trino supports and will soon require Java 17 to
```suggestion
interesting time as [Trino now requires Java 17 to 
```

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +can take to write your own query engine...at least if you want to do it the way
```suggestion
can take to write your own query engine, at least if you want to do it the way
```

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +1. Expand outside the initial use cases at Facebook by learning from other
```suggestion
1. Expand outside the initial use cases by learning from other
```

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +
remove empty line

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +After a lot of the initial work was done, Martin, Dain, David, and Eric finally
This sentence makes no sense.

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +paid off. Prest was deployed at Facebook and soon after open sourced. From here,
```suggestion
paid off. Presto was deployed at Facebook and soon after open sourced. From here,
```

2022-09-09 22:27 UTC, mosabua commented on _posts/2022-09-08-tenth-birthday-celebration-recap.md
> +We hoped you enjoyed all the fun we had celebrating these first ten years of the
```suggestion
We hope you enjoyed all the fun we had celebrating the first ten years of the
```

2022-09-12 17:53 UTC, mosabua requested changes

2022-09-12 17:53 UTC, mosabua commented on _posts/2022-09-12-tenth-birthday-celebration-recap.md
> +bring. We'd like to leave you with a closing though from Dain around what the
```suggestion
bring. We'd like to leave you with closing thoughts from Dain:
```

2022-09-12 17:53 UTC, mosabua commented on _posts/2022-09-12-tenth-birthday-celebration-recap.md
> +next ten years of Trino will look like:
remove

2022-09-12 18:08 UTC, mosabua approved these changes
Good to go now as well! 💥

2022-09-12 18:15 UTC, bitsondatadev commented
> Uff .. just noticed .. hn-9.png is not used .. either use or delete

Deleted and merging!

2022-09-12 18:15 UTC, merged

2022-09-12 18:31 UTC, mosabua commented
Sweet..