Trino Summit Teaser post
trinodb/trino.io pull request #351
Opened 2022-09-22 21:00 UTC by bitsondatadev

2022-09-22 21:36 UTC, mosabua requested changes

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +Bun Bun is back and this year we have an exciting lineup of speakers. The range
```suggestion
Commander Bun Bun is back, and this year we have an exciting lineup of speakers. The range
```

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +of topics span from architectures like data mesh and data lakehouses, to running
```suggestion
of topics spans from architectures like data mesh and data lakehouses, to running
```

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +Trino at scale with fault-tolerance and how to use `EXPLAIN`. This conference is
```suggestion
Trino at scale with fault-tolerant execution and how to use `EXPLAIN`. This conference is
```

maybe even break up the sentence

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +free and takes place on November 10th. The summit is in-person but also is
The summit is a hybrid even for in-person and virtual attendance.

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +
Add the button from the other blog post here

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +1. Keynote: State of Trino
Add an entry sentence that mentions that call for speakers closed and we have a full line up .. and here are a first few teasers

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +    * <img width="150" src="https://sessionize.com/image/40f9-0o0o0-Jd9Ri1YsJ7VyFniPcENpHv.jpg">
Let not use images from sessionize .. either dont use them .. or get them into the site directly

2022-09-22 21:36 UTC, mosabua commented on _posts/2022-09-16-trino-summit-2022-teaser.md
> +    * <img width="150" src="https://sessionize.com/image/40f9-0o0o0-Jd9Ri1YsJ7VyFniPcENpHv.jpg">
Just the names are perfectly fine as well btw. .. images are not really necessary

2022-09-22 22:04 UTC, mosabua requested changes

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +**Speakers:**
do we need this subtitle .. its kinda obvious .. might work fine without

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +* Martin Traverso, Co-Creator of Trino and Chief Technology Officer, Starburst
just use CTO

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +### Trino for Large Scale ETL at Lyft
```suggestion
### Trino for large scale ETL at Lyft
```

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +**Abstract:** Hear the latest on the state of the open source Trino project. Trino
I dont think we nee "Abstract"

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +### Rewriting History: Migrating petabytes of data to Apache Iceberg using Trino
history

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +### Federating them all on Galaxy!
```suggestion
### Federating them all on Starburst Galaxy!
```

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +Galaxy is the fastest path to query federation and cover a demo that trainers
```suggestion
Starburst Galaxy is the fastest path to query federation and cover a demo that trainers
```

2022-09-22 22:04 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +register, and always federate them all!
make register a link here as well

2022-09-22 22:13 UTC, bitsondatadev commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +is the award-winning MPP SQL query engine. In this session, Trino and Presto
the InfoWorld BOSSIE awards among others like that.

2022-09-23 10:47 UTC, bitsondatadev commented
Just added the link from the homepage banner.

2022-09-23 16:27 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +author: "Brian Olsen"
we should add Dain as author .. he is in the video ;-)

2022-09-23 16:30 UTC, mosabua requested changes
Minor nits.. lets ship it!

2022-09-23 16:30 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +image: /assets/blog/trino-summit-2022/summit-logo.png
Nice catch to add that ..

2022-09-23 16:30 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +to running Trino at scale with fault-tolerant execution and query federation.
```suggestion
to running Trino at scale with fault-tolerant execution, and query federation.
```

2022-09-23 16:30 UTC, mosabua commented on _posts/2022-09-22-trino-summit-2022-teaser.md
> +⚡ _Lightning talk_
drop that .. unimportant detail ;-)

2022-09-23 17:47 UTC, mosabua commented
Also .. we need to make the video public just before we merge...

2022-09-23 18:25 UTC, mosabua approved these changes
Federate them all!

2022-09-23 18:26 UTC, merged