Add Quora recap post
trinodb/trino.io pull request #390
Opened 2022-12-15 10:55 UTC by colebow

2022-12-15 10:57 UTC, colebow commented
Netlify looks angry, but it's building fine locally.

2022-12-15 22:45 UTC, colebow commented
Social card has a weird link in the middle of it, not sure where it came from, but we'll need to get that fixed before we merge.

2022-12-15 23:21 UTC, mosabua requested changes

2022-12-15 23:21 UTC, mosabua commented on _posts/2022-12-16-trino-summit-2022-quora-recap.md
> +Trino, and other Trino users may be able to learn a few neat tips and tricks to
```suggestion
Trino. Other Trino users may be able to learn a few neat tips and tricks to
```

2022-12-15 23:21 UTC, mosabua commented on _posts/2022-12-16-trino-summit-2022-quora-recap.md
> +queries from a variety of clients and services and then executes those queries
```suggestion
queries from a variety of clients and services, and then executes those queries
```

2022-12-15 23:21 UTC, mosabua commented on _posts/2022-12-16-trino-summit-2022-quora-recap.md
> +for 24+ hours straight would utilize less CPU and run slow, bogging things down.
24 hours or more

2022-12-15 23:21 UTC, mosabua commented on _posts/2022-12-16-trino-summit-2022-quora-recap.md
> +tools to track the health of their Trino clusters, ensuring that even when user
```suggestion
tools to track the health of their Trino clusters. They ensure that even when user
```

and adjust the rest of the sentence

2022-12-15 23:28 UTC, mosabua approved these changes
Looks good now.

2022-12-16 18:25 UTC, bitsondatadev approved these changes
Looks great! Thanks Cole!

2022-12-16 18:26 UTC, merged