Add episode 46
trinodb/trino.io pull request #415
Opened 2023-03-14 22:46 UTC by colebow

2023-03-14 23:20 UTC, mosabua requested changes

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +tags: datbase memory in-memory ignite
```suggestion
tags: database memory in-memory apache ignite
```

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +- title: "Trino Release"
```suggestion
- title: "Trino releases"
```

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +be familiar with like SQL Server, Redis, and SingleStore. If you're not familiar
SQL Server ?? really .. I think of it as a traditional RDBMS

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +With an initial release 7 years ago, Ignite is still something of the new kid on
something of the new kid .... sounds weird

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +## Ignite + Trino
```suggestion
## Ignite and Trino
```

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +To give you an idea, the pull request (PR) to contribute Ignite was opened in
we should link to the PR

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +it run. Neat, right?
Do we want to talk about what this does? Even high level  .. I assume it creates metadata in the Iceberg format, wipes most metadata in the HMS, and then updates the HMS to reference the iceberg format

2023-03-14 23:20 UTC, mosabua commented on _episodes/46.md
> +the [Trino events calendar]({{site.url}}/community.html#events).
Call out Boston event

2023-03-15 06:38 UTC, chenjian2664 commented on _episodes/46.md
> +date: 2023-02-23
Should be 2023-03-16?

2023-03-15 06:38 UTC, chenjian2664 commented on _episodes/46.md
> +* Jason (please comment however you'd like this to introduce you)
[Jason](https://www.linkedin.com/in/jian-chen-7aa3a2225) Senior data engineer at Shopee.

2023-03-15 17:31 UTC, mosabua commented on _episodes/46.md
> +date: 2023-02-23
or 15 ...

2023-03-21 02:09 UTC, bitsondatadev approved these changes
![image](https://user-images.githubusercontent.com/8547669/226503008-54b230b6-f919-42cd-8069-03820dedf024.png)

2023-03-21 02:11 UTC, merged