Add recap post for zero-cost reporting
trinodb/trino.io pull request #465
Opened 2023-06-27 18:59 UTC by colebow

2023-06-27 19:58 UTC, mosabua requested changes
Two things only .. pretty much ready to roll.

2023-06-27 19:58 UTC, mosabua commented on _posts/2023-06-28-trino-fest-2023-starburst-recap.md
> +Let's say you have some data. Maybe it's in a spreadsheet, a CSV file, a
I feel like this paragraph is a bit long to be all before the "more" break. Can we separate it up somehow?

2023-06-27 19:58 UTC, mosabua commented on _posts/2023-06-28-trino-fest-2023-starburst-recap.md
> +results without the need for any manual effort on your part. There are a lot of
Maybe break here?

2023-06-27 19:58 UTC, mosabua commented on _posts/2023-06-28-trino-fest-2023-starburst-recap.md
> +
Slide deck is missing

2023-06-27 20:00 UTC, ryandoowan commented on _posts/2023-06-28-trino-fest-2023-starburst-recap.md
> +need to spend time or money to set it up, and you don't want to spend a lot.
The second part feels a bit redundant

2023-06-27 20:03 UTC, ryandoowan commented on _posts/2023-06-28-trino-fest-2023-starburst-recap.md
> +With so many options, there's the possibility to get stuck in analysis
possibility of getting stuck

2023-06-27 22:50 UTC, mosabua approved these changes

2023-06-28 15:31 UTC, ryandoowan approved these changes

2023-06-28 15:44 UTC, merged