Add Apache Iceberg blog post
trinodb/trino.io pull request #467
Opened 2023-06-29 19:44 UTC by ryandoowan

2023-06-29 19:45 UTC, ryandoowan commented
@mosabua @colebow @bitsondatadev

2023-06-29 19:52 UTC, mosabua requested changes

2023-06-29 19:52 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +Have you ever needed to keep your data all in a table and an efficient way to
that sentence reads weirdly

2023-06-29 19:52 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +interact with them? Iceberg, an open standard for tables with SQL behavior, is
```suggestion
interact with them? Iceberg, an open standard table format, is
```

2023-06-29 19:52 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +exactly what you need. But what makes Iceberg unique is its use of change data
```suggestion
exactly what you need. What makes Iceberg unique is its use of change data
```

2023-06-29 19:52 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +prefer it to be faster or slower. The Flink UPSERT pattern is an update type
Remove the Flink stuff

2023-06-29 19:52 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +
Do we need some sort of "watch the video and slides for more details" @colebow  .. I kinda of think maybe yes.. but also maybe not .. 

How about just a final closure sentence?

2023-06-30 03:15 UTC, mosabua requested changes

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +exactly what you need. What makes Iceberg unique is its use of change data
```suggestion
exactly what you need. On of the great and unique features of the Iceberg tableformat is its support for of change data
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +capture (CDC). Co-creator of Apache Iceberg, Ryan Blue, gave a talk at [Trino Fest 2023]({% post_url
```suggestion
capture (CDC). Co-creator of Apache Iceberg, Ryan Blue, presented at [Trino Fest 2023]({% post_url
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +2023-06-20-trino-fest-2023-recap %}) this past week detailing the trade-offs
```suggestion
2023-06-20-trino-fest-2023-recap %}) this past week detailing the CDC support and the trade-offs
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +between each pattern that can be used for writing CDC streams into Iceberg
```suggestion
between different patterns that can be used for writing CDC streams into Iceberg
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +To begin, what is CDC and why should you use it? CDC is the idea that relational
```suggestion
To begin, what is CDC and why should you use it? CDC is the idea that when relational
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +or transactional tables are modified, you emit an update stream to keep copies
```suggestion
or transactional tables are modified, you emit an update stream. This enables you to keep copies
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +in sync so that you capture changes to tables as they happen. As Ryan states,
```suggestion
in sync by capturing changes to tables as they happen. As Ryan states,
```

2023-06-30 03:15 UTC, mosabua commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +
Maybe something like

He mentions that with Iceberg you have the choice and the different CDC patterns can be supported and you can adjust your usage to your specific needs. Watch the video and review the slides for more details.

2023-06-30 08:16 UTC, colebow commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +trade-off that Ryan talks about is the storage trade-offs between using direct
Need to decide whether this is singular or plural. "The first trade-off... is the trade-offs" doesn't work.

2023-06-30 08:16 UTC, colebow commented on _posts/2023-06-30-trino-fest-2023-apacheiceberg.md
> +prefer it to be faster or slower. The change log pattern and MERGE pattern both
```suggestion
prefer it to be faster or slower. The change log pattern and `MERGE` pattern both
```
Ticks will give it syntax highlighting.

2023-06-30 16:31 UTC, mosabua approved these changes

2023-06-30 16:31 UTC, merged