Dune
trinodb/trino.io pull request #482
Opened 2023-07-12 22:20 UTC by ryandoowan

2023-07-12 23:03 UTC, mosabua requested changes
MAybe address the comment and then we have a call to chat more about the last big paragraph.

2023-07-12 23:03 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +scheme and our datasets." Using Trino helped their performance issues and made
```suggestion
scheme and our datasets." Using Trino addressed the performance issues.
```

2023-07-12 23:03 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +their queries run faster than previous SQLs.
remove this line

2023-07-12 23:03 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +Operating DuneSQL requires more modification and extending Trino to suit the
This whole paragraph is a bit mixed up.

2023-07-12 23:16 UTC, colebow requested changes

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +their own query engine called DuneSQL, a fork of TrinoSQL, to query blockchain
```suggestion
their own query engine called DuneSQL, a fork of Trino, to query blockchain
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +data. In Miguel and Jonas' talk, they talk about the challenges in querying
```suggestion
data. In the talk, Miguel and Jonas from Dune talk about the challenges in querying
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +However, they have some difficulties with blockchain data such as processing and
```suggestion
However, they have some difficulties with blockchain data, such as processing and
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +has 10000s of queries that are executed and saved and re-used each day.
```suggestion
has tens of thousands of queries that are executed, saved, and re-used each day.
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +At first, Dune used PostgreSQL where they sharded per blockchain and used a
```suggestion
At first, Dune used PostgreSQL, where they sharded per blockchain and used a
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +size and IOPS. Thus, they switched to Spark/Databricks for a horizontal scaling
IOPS probably needs to be spelled out, maybe in parentheses. Not an acronym you encounter super frequently.

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +in order to adopt much more blockchains and to support the vast query volume
```suggestion
in order to adopt more blockchains and to support the vast query volume
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +that they had, but this was not interactive enough and was often tied to the
```suggestion
that they had. Unfortunately, this was not interactive enough and was often tied to the
```
Let's break it up into two sentences.

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +vendor. In the end, Miguel says in that "Trino was our choice for performance
```suggestion
vendor. In the end, Miguel says in that, "Trino was our choice for performance
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +their queries run faster than previous SQLs.
```suggestion
their queries run faster than previous SQL engines.
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +Operating DuneSQL requires more modification and extending Trino to suit the
```suggestion
Operating DuneSQL requires modifications and extensions of Trino to suit the
```

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +needs of the users and platform as a whole. DuneSQL is able to handle 10000s of
tens of thousands again

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +addition, they use query execution services and Trino-Gateway to handle the
Embed a hyperlink to gateway: https://github.com/lyft/presto-gateway

2023-07-12 23:16 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +receive, improve data layout, and implementing sandboxed user defined functions.
```suggestion
receive, improve data layout, and implement sandboxed user defined functions.
```
Keep tense consistent.

2023-07-13 20:59 UTC, colebow approved these changes
A few tiny nits

2023-07-13 20:59 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +Dune has made this their mission to make crypto data more accessible. Dune is a
```suggestion
Dune has made it their mission to make crypto data more accessible. Dune is a
```

2023-07-13 20:59 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +The Dune community data platform is a serverless, open access, community wide
```suggestion
The Dune community data platform is a serverless, open access, community-wide
```

2023-07-13 20:59 UTC, colebow commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +and performance, and to reduce the blast-radius so it does not affect other
```suggestion
and performance and to reduce the blast-radius so it does not affect other
```

2023-07-13 21:52 UTC, mosabua requested changes

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +years due to the rise of cryptocurrencies, NFTs, and other uses of blockchains.
```suggestion
years due to the popularity of cryptocurrencies, NFTs, and other uses of blockchains.
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +Dune has made it their mission to make crypto data more accessible. Dune is a
```suggestion
Dune has made it their mission to make blockchain data more accessible. Dune is a
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +beautiful dashboards. They use their own query engine called DuneSQL, a fork of
```suggestion
beautiful dashboards. They use their own query engine called DuneSQL, built as extension of 
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +Trino, to query blockchain data. In the talk, Miguel and Jonas from Dune talk
```suggestion
Trino, to query blockchain data. In the session, Miguel and Jonas from Dune talk
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +how DuneSQL is operated. Give the talk a listen or keep reading for a recap.
```suggestion
how DuneSQL is operated. Watch the recording of the session or keep reading for a recap.
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +addition, their engine, DuneSQL, is Trino with custom extensions that they
Remove "In addition"

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +At first, Dune used PostgreSQL, where they sharded per blockchain and used a
```suggestion
At first, Dune used PostgreSQL, where they sharded per blockchain and used
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +In addition, operating DuneSQL requires modifications and extensions of Trino to
```suggestion
Operating DuneSQL requires modifications and extensions of Trino to
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +operations, DuneSQL use query execution services and
```suggestion
operations, DuneSQL uses query execution services and the
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +[Trino-Gateway](https://github.com/lyft/presto-gateway). To manage clusters,
```suggestion
[gateway](https://github.com/lyft/presto-gateway).
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +they make it have a fixed size in order for it to have a predictable capacity
```suggestion
Clusters have a fixed size to have a predictable capacity
```

2023-07-13 21:52 UTC, mosabua commented on _posts/2023-07-14-trino-fest-2023-dune.md
> +and performance and to reduce the blast-radius so it does not affect other
```suggestion
and performance. The gateway exposes the clusters to reduce the blast-radius so failures do not affect other
```

2023-07-14 16:39 UTC, mosabua approved these changes

2023-07-14 16:40 UTC, merged