Add DolphinScheduler client tool
trinodb/trino.io pull request #504
Opened 2023-07-21 17:01 UTC by ryandoowan

2023-07-21 22:20 UTC, mosabua requested changes

2023-07-26 22:21 UTC, mosabua commented on _data/tools.yml
> +    - urltext: Apache DolphinScheduler documentation
Lets leave the documentation link out for now. We should ping them to add a Trino specific page..

2023-07-26 22:22 UTC, mosabua requested changes
Minor change

2023-07-26 22:22 UTC, mosabua commented
Also .. you need to rebase..

2023-07-26 22:54 UTC, closed without merging

2023-07-26 22:55 UTC, ryandoowan commented
Ok something happened when I tried to rebase, I'm making a new PR