Add Rudderstack as add-on
trinodb/trino.io pull request #576
Opened 2023-12-11 19:09 UTC by mosabua

2023-12-11 19:36 UTC, ericdodds requested changes
A few updates: 

```
logo: /assets/images/logos/rudderstack.png
  logosmall: /assets/images/logos/rudderstack-small.png
  description: |
    tbd
    RudderStack's reverse ETL pipeline now supports Trino as a source. This integration makes it easy to sync data from Trino to over 200 destinations so every team can use it to drive better business outcomes. The integration supports warehouse-based diffing, making it the most performant Reverse ETL solution for Trino.
  links:
    - urltext: rudderstack
      url: https://www.rudderstack.com/
    - urltext: Trino as reverse ETL source with rudderstack
      url: https://www.rudderstack.com/blog/feature-launch-trino-reverse-etl-source/
      url: https://www.rudderstack.com/docs/sources/reverse-etl/trino/
- name: SingleStore
  anchor: singlestore
  category: data-source
```

2023-12-15 20:20 UTC, mosabua commented
Let me know if this looks good now @ericdodds

2023-12-18 17:32 UTC, ericdodds commented
@mosabua Looks great, thanks

2023-12-18 17:42 UTC, martint approved these changes

2023-12-18 17:55 UTC, merged